# Especificamos a versão do Docker Compose
# version: '3.9'

# Definimos os volumes para persistência de dados
volumes:
  mysql_data: {}

# Definimos os serviços que serão executados
services:
  # Serviço do MySQL
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # Serviço do WordPress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
